### ISSUE TITLE
Build not flashable on XQ-CQ54

### ISSUE THREAD

**Issue by ekaats** [XperiaLabs/device_sony_pdx225#4]
The current build is not flashable on the eSim + Sim model (XQ-CQ54). When trying to flash, it refuses, saying it is meant for XQ-CQ72.

After modifying the files and building again, it does flash as expected.

**Comment by ghost** [comment]
fixed with https://github.com/XperiaLabs/device_sony_pdx225/commit/238b46c20d1ffc7ef47d6498ed14b968bd0b1359
